"""Initial migration

Revision ID: 094c9a2560c7
Revises: 
Create Date: 2026-01-06 17:24:09.537850

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '094c9a2560c7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.add_column('leaves', sa.Column('emp_id', sa.String(), nullable=True))
    op.add_column('leaves', sa.Column('leave_date', sa.Date(), nullable=False))
    op.add_column('leaves', sa.Column('reason', sa.String(), nullable=True))
    op.add_column('leaves', sa.Column('status', sa.String(), nullable=True))
    op.add_column('leaves', sa.Column('applied_at', sa.DateTime(), nullable=True))
    op.add_column('leaves', sa.Column('approved_by', sa.String(), nullable=True))
    op.add_column('leaves', sa.Column('approved_at', sa.DateTime(), nullable=True))
    op.create_foreign_key(None, 'leaves', 'employees', ['emp_id'], ['emp_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'leaves', type_='foreignkey')
    op.drop_column('leaves', 'approved_at')
    op.drop_column('leaves', 'approved_by')
    op.drop_column('leaves', 'applied_at')
    op.drop_column('leaves', 'status')
    op.drop_column('leaves', 'reason')
    op.drop_column('leaves', 'leave_date')
    op.drop_column('leaves', 'emp_id')
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('role', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('users_pkey'))
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###
